// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/auction/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auction "github.com/dreamers-be/internal/domain/auction"
	gomock "github.com/golang/mock/gomock"
)

// MockTournamentRepository is a mock of TournamentRepository interface.
type MockTournamentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentRepositoryMockRecorder
}

// MockTournamentRepositoryMockRecorder is the mock recorder for MockTournamentRepository.
type MockTournamentRepositoryMockRecorder struct {
	mock *MockTournamentRepository
}

// NewMockTournamentRepository creates a new mock instance.
func NewMockTournamentRepository(ctrl *gomock.Controller) *MockTournamentRepository {
	mock := &MockTournamentRepository{ctrl: ctrl}
	mock.recorder = &MockTournamentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentRepository) EXPECT() *MockTournamentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTournamentRepository) Create(ctx context.Context, t *auction.Tournament) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTournamentRepositoryMockRecorder) Create(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTournamentRepository)(nil).Create), ctx, t)
}

// GetByID mocks base method.
func (m *MockTournamentRepository) GetByID(ctx context.Context, id string) (*auction.Tournament, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*auction.Tournament)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTournamentRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTournamentRepository)(nil).GetByID), ctx, id)
}

// MockTournamentEventRepository is a mock of TournamentEventRepository interface.
type MockTournamentEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentEventRepositoryMockRecorder
}

// MockTournamentEventRepositoryMockRecorder is the mock recorder for MockTournamentEventRepository.
type MockTournamentEventRepositoryMockRecorder struct {
	mock *MockTournamentEventRepository
}

// NewMockTournamentEventRepository creates a new mock instance.
func NewMockTournamentEventRepository(ctrl *gomock.Controller) *MockTournamentEventRepository {
	mock := &MockTournamentEventRepository{ctrl: ctrl}
	mock.recorder = &MockTournamentEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentEventRepository) EXPECT() *MockTournamentEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTournamentEventRepository) Create(ctx context.Context, te *auction.TournamentEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, te)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTournamentEventRepositoryMockRecorder) Create(ctx, te interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTournamentEventRepository)(nil).Create), ctx, te)
}

// GetByID mocks base method.
func (m *MockTournamentEventRepository) GetByID(ctx context.Context, id string) (*auction.TournamentEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*auction.TournamentEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTournamentEventRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTournamentEventRepository)(nil).GetByID), ctx, id)
}

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, team *auction.TournamentTeamRegistration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, team)
}

// GetByID mocks base method.
func (m *MockTeamRepository) GetByID(ctx context.Context, id string) (*auction.TournamentTeamRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*auction.TournamentTeamRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamRepository)(nil).GetByID), ctx, id)
}

// ListByTournamentEvent mocks base method.
func (m *MockTeamRepository) ListByTournamentEvent(ctx context.Context, tournamentID, tournamentEventID string) ([]*auction.TournamentTeamRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTournamentEvent", ctx, tournamentID, tournamentEventID)
	ret0, _ := ret[0].([]*auction.TournamentTeamRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTournamentEvent indicates an expected call of ListByTournamentEvent.
func (mr *MockTeamRepositoryMockRecorder) ListByTournamentEvent(ctx, tournamentID, tournamentEventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTournamentEvent", reflect.TypeOf((*MockTeamRepository)(nil).ListByTournamentEvent), ctx, tournamentID, tournamentEventID)
}

// MockRegistrationRepository is a mock of RegistrationRepository interface.
type MockRegistrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationRepositoryMockRecorder
}

// MockRegistrationRepositoryMockRecorder is the mock recorder for MockRegistrationRepository.
type MockRegistrationRepositoryMockRecorder struct {
	mock *MockRegistrationRepository
}

// NewMockRegistrationRepository creates a new mock instance.
func NewMockRegistrationRepository(ctrl *gomock.Controller) *MockRegistrationRepository {
	mock := &MockRegistrationRepository{ctrl: ctrl}
	mock.recorder = &MockRegistrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationRepository) EXPECT() *MockRegistrationRepositoryMockRecorder {
	return m.recorder
}

// AssignToTeam mocks base method.
func (m *MockRegistrationRepository) AssignToTeam(ctx context.Context, registrationID, teamRegistrationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignToTeam", ctx, registrationID, teamRegistrationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignToTeam indicates an expected call of AssignToTeam.
func (mr *MockRegistrationRepositoryMockRecorder) AssignToTeam(ctx, registrationID, teamRegistrationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignToTeam", reflect.TypeOf((*MockRegistrationRepository)(nil).AssignToTeam), ctx, registrationID, teamRegistrationID)
}

// GetByID mocks base method.
func (m *MockRegistrationRepository) GetByID(ctx context.Context, id string) (*auction.TournamentPlayerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*auction.TournamentPlayerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRegistrationRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRegistrationRepository)(nil).GetByID), ctx, id)
}

// ListEligible mocks base method.
func (m *MockRegistrationRepository) ListEligible(ctx context.Context, tournamentID, tournamentEventID string, f auction.RegistrationFilter) ([]*auction.TournamentPlayerRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEligible", ctx, tournamentID, tournamentEventID, f)
	ret0, _ := ret[0].([]*auction.TournamentPlayerRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEligible indicates an expected call of ListEligible.
func (mr *MockRegistrationRepositoryMockRecorder) ListEligible(ctx, tournamentID, tournamentEventID, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEligible", reflect.TypeOf((*MockRegistrationRepository)(nil).ListEligible), ctx, tournamentID, tournamentEventID, f)
}

// UnassignTeam mocks base method.
func (m *MockRegistrationRepository) UnassignTeam(ctx context.Context, registrationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignTeam", ctx, registrationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignTeam indicates an expected call of UnassignTeam.
func (mr *MockRegistrationRepositoryMockRecorder) UnassignTeam(ctx, registrationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignTeam", reflect.TypeOf((*MockRegistrationRepository)(nil).UnassignTeam), ctx, registrationID)
}

// MockAuctionRepository is a mock of AuctionRepository interface.
type MockAuctionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuctionRepositoryMockRecorder
}

// MockAuctionRepositoryMockRecorder is the mock recorder for MockAuctionRepository.
type MockAuctionRepositoryMockRecorder struct {
	mock *MockAuctionRepository
}

// NewMockAuctionRepository creates a new mock instance.
func NewMockAuctionRepository(ctrl *gomock.Controller) *MockAuctionRepository {
	mock := &MockAuctionRepository{ctrl: ctrl}
	mock.recorder = &MockAuctionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuctionRepository) EXPECT() *MockAuctionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuctionRepository) Create(ctx context.Context, a *auction.Auction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuctionRepositoryMockRecorder) Create(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuctionRepository)(nil).Create), ctx, a)
}

// GetByID mocks base method.
func (m *MockAuctionRepository) GetByID(ctx context.Context, id string) (*auction.Auction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*auction.Auction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuctionRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuctionRepository)(nil).GetByID), ctx, id)
}

// UpdateRunMode mocks base method.
func (m *MockAuctionRepository) UpdateRunMode(ctx context.Context, auctionID string, runMode auction.AuctionRunMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunMode", ctx, auctionID, runMode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunMode indicates an expected call of UpdateRunMode.
func (mr *MockAuctionRepositoryMockRecorder) UpdateRunMode(ctx, auctionID, runMode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunMode", reflect.TypeOf((*MockAuctionRepository)(nil).UpdateRunMode), ctx, auctionID, runMode)
}

// UpdateStatus mocks base method.
func (m *MockAuctionRepository) UpdateStatus(ctx context.Context, auctionID string, status auction.AuctionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, auctionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAuctionRepositoryMockRecorder) UpdateStatus(ctx, auctionID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAuctionRepository)(nil).UpdateStatus), ctx, auctionID, status)
}

// UpdateDisplayAuctionPlayer mocks base method.
func (m *MockAuctionRepository) UpdateDisplayAuctionPlayer(ctx context.Context, auctionID, auctionPlayerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisplayAuctionPlayer", ctx, auctionID, auctionPlayerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDisplayAuctionPlayer indicates an expected call of UpdateDisplayAuctionPlayer.
func (mr *MockAuctionRepositoryMockRecorder) UpdateDisplayAuctionPlayer(ctx, auctionID, auctionPlayerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisplayAuctionPlayer", reflect.TypeOf((*MockAuctionRepository)(nil).UpdateDisplayAuctionPlayer), ctx, auctionID, auctionPlayerID)
}

// MockAuctionPlayerRepository is a mock of AuctionPlayerRepository interface.
type MockAuctionPlayerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuctionPlayerRepositoryMockRecorder
}

// MockAuctionPlayerRepositoryMockRecorder is the mock recorder for MockAuctionPlayerRepository.
type MockAuctionPlayerRepositoryMockRecorder struct {
	mock *MockAuctionPlayerRepository
}

// NewMockAuctionPlayerRepository creates a new mock instance.
func NewMockAuctionPlayerRepository(ctrl *gomock.Controller) *MockAuctionPlayerRepository {
	mock := &MockAuctionPlayerRepository{ctrl: ctrl}
	mock.recorder = &MockAuctionPlayerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuctionPlayerRepository) EXPECT() *MockAuctionPlayerRepositoryMockRecorder {
	return m.recorder
}

// ClearSale mocks base method.
func (m *MockAuctionPlayerRepository) ClearSale(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSale", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSale indicates an expected call of ClearSale.
func (mr *MockAuctionPlayerRepositoryMockRecorder) ClearSale(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSale", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).ClearSale), ctx, id)
}

// Create mocks base method.
func (m *MockAuctionPlayerRepository) Create(ctx context.Context, ap *auction.AuctionPlayer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuctionPlayerRepositoryMockRecorder) Create(ctx, ap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).Create), ctx, ap)
}

// GetByID mocks base method.
func (m *MockAuctionPlayerRepository) GetByID(ctx context.Context, id string) (*auction.AuctionPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*auction.AuctionPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuctionPlayerRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).GetByID), ctx, id)
}

// GetByAuctionAndRegistrationSerial mocks base method.
func (m *MockAuctionPlayerRepository) GetByAuctionAndRegistrationSerial(ctx context.Context, auctionID string, serialNumber int) (*auction.AuctionPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAuctionAndRegistrationSerial", ctx, auctionID, serialNumber)
	ret0, _ := ret[0].(*auction.AuctionPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAuctionAndRegistrationSerial indicates an expected call of GetByAuctionAndRegistrationSerial.
func (mr *MockAuctionPlayerRepositoryMockRecorder) GetByAuctionAndRegistrationSerial(ctx, auctionID, serialNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAuctionAndRegistrationSerial", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).GetByAuctionAndRegistrationSerial), ctx, auctionID, serialNumber)
}

// ListByAuction mocks base method.
func (m *MockAuctionPlayerRepository) ListByAuction(ctx context.Context, auctionID string) ([]*auction.AuctionPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuction", ctx, auctionID)
	ret0, _ := ret[0].([]*auction.AuctionPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAuction indicates an expected call of ListByAuction.
func (mr *MockAuctionPlayerRepositoryMockRecorder) ListByAuction(ctx, auctionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuction", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).ListByAuction), ctx, auctionID)
}

// ListByAuctionWithPlayerFilter mocks base method.
func (m *MockAuctionPlayerRepository) ListByAuctionWithPlayerFilter(ctx context.Context, auctionID string, f auction.RegistrationFilter, registrationSerial int, soldToTeamRegistrationID string) ([]*auction.AuctionPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuctionWithPlayerFilter", ctx, auctionID, f, registrationSerial, soldToTeamRegistrationID)
	ret0, _ := ret[0].([]*auction.AuctionPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAuctionWithPlayerFilter indicates an expected call of ListByAuctionWithPlayerFilter.
func (mr *MockAuctionPlayerRepositoryMockRecorder) ListByAuctionWithPlayerFilter(ctx, auctionID, f, registrationSerial, soldToTeamRegistrationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuctionWithPlayerFilter", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).ListByAuctionWithPlayerFilter), ctx, auctionID, f, registrationSerial, soldToTeamRegistrationID)
}

// MarkSold mocks base method.
func (m *MockAuctionPlayerRepository) MarkSold(ctx context.Context, id string, finalPrice int64, soldToTeamRegistrationID string, notes auction.AuctionPlayerNotes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSold", ctx, id, finalPrice, soldToTeamRegistrationID, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSold indicates an expected call of MarkSold.
func (mr *MockAuctionPlayerRepositoryMockRecorder) MarkSold(ctx, id, finalPrice, soldToTeamRegistrationID, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSold", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).MarkSold), ctx, id, finalPrice, soldToTeamRegistrationID, notes)
}

// UpdateStatus mocks base method.
func (m *MockAuctionPlayerRepository) UpdateStatus(ctx context.Context, id string, status auction.AuctionPlayerStatus, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAuctionPlayerRepositoryMockRecorder) UpdateStatus(ctx, id, status, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).UpdateStatus), ctx, id, status, isActive)
}

// ResetAllLotsToPending mocks base method.
func (m *MockAuctionPlayerRepository) ResetAllLotsToPending(ctx context.Context, auctionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAllLotsToPending", ctx, auctionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAllLotsToPending indicates an expected call of ResetAllLotsToPending.
func (mr *MockAuctionPlayerRepositoryMockRecorder) ResetAllLotsToPending(ctx, auctionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAllLotsToPending", reflect.TypeOf((*MockAuctionPlayerRepository)(nil).ResetAllLotsToPending), ctx, auctionID)
}

// MockBidRepository is a mock of BidRepository interface.
type MockBidRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBidRepositoryMockRecorder
}

// MockBidRepositoryMockRecorder is the mock recorder for MockBidRepository.
type MockBidRepositoryMockRecorder struct {
	mock *MockBidRepository
}

// NewMockBidRepository creates a new mock instance.
func NewMockBidRepository(ctrl *gomock.Controller) *MockBidRepository {
	mock := &MockBidRepository{ctrl: ctrl}
	mock.recorder = &MockBidRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBidRepository) EXPECT() *MockBidRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBidRepository) Create(ctx context.Context, b *auction.Bid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBidRepositoryMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBidRepository)(nil).Create), ctx, b)
}

// GetHighestBid mocks base method.
func (m *MockBidRepository) GetHighestBid(ctx context.Context, auctionPlayerID string) (*auction.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestBid", ctx, auctionPlayerID)
	ret0, _ := ret[0].(*auction.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighestBid indicates an expected call of GetHighestBid.
func (mr *MockBidRepositoryMockRecorder) GetHighestBid(ctx, auctionPlayerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestBid", reflect.TypeOf((*MockBidRepository)(nil).GetHighestBid), ctx, auctionPlayerID)
}

// DeleteLatestByAuctionPlayer mocks base method.
func (m *MockBidRepository) DeleteLatestByAuctionPlayer(ctx context.Context, auctionPlayerID string) (*auction.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLatestByAuctionPlayer", ctx, auctionPlayerID)
	ret0, _ := ret[0].(*auction.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLatestByAuctionPlayer indicates an expected call of DeleteLatestByAuctionPlayer.
func (mr *MockBidRepositoryMockRecorder) DeleteLatestByAuctionPlayer(ctx, auctionPlayerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLatestByAuctionPlayer", reflect.TypeOf((*MockBidRepository)(nil).DeleteLatestByAuctionPlayer), ctx, auctionPlayerID)
}

// ListByAuctionPlayer mocks base method.
func (m *MockBidRepository) ListByAuctionPlayer(ctx context.Context, auctionPlayerID string) ([]*auction.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuctionPlayer", ctx, auctionPlayerID)
	ret0, _ := ret[0].([]*auction.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAuctionPlayer indicates an expected call of ListByAuctionPlayer.
func (mr *MockBidRepositoryMockRecorder) ListByAuctionPlayer(ctx, auctionPlayerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuctionPlayer", reflect.TypeOf((*MockBidRepository)(nil).ListByAuctionPlayer), ctx, auctionPlayerID)
}

// DeleteByAuction mocks base method.
func (m *MockBidRepository) DeleteByAuction(ctx context.Context, auctionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAuction", ctx, auctionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAuction indicates an expected call of DeleteByAuction.
func (mr *MockBidRepositoryMockRecorder) DeleteByAuction(ctx, auctionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAuction", reflect.TypeOf((*MockBidRepository)(nil).DeleteByAuction), ctx, auctionID)
}

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockWalletRepository) CreateTransaction(ctx context.Context, tx *auction.WalletTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockWalletRepositoryMockRecorder) CreateTransaction(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockWalletRepository)(nil).CreateTransaction), ctx, tx)
}

// GetByTournamentEventTeam mocks base method.
func (m *MockWalletRepository) GetByTournamentEventTeam(ctx context.Context, tournamentID, tournamentEventID, teamRegistrationID string) (*auction.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTournamentEventTeam", ctx, tournamentID, tournamentEventID, teamRegistrationID)
	ret0, _ := ret[0].(*auction.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTournamentEventTeam indicates an expected call of GetByTournamentEventTeam.
func (mr *MockWalletRepositoryMockRecorder) GetByTournamentEventTeam(ctx, tournamentID, tournamentEventID, teamRegistrationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTournamentEventTeam", reflect.TypeOf((*MockWalletRepository)(nil).GetByTournamentEventTeam), ctx, tournamentID, tournamentEventID, teamRegistrationID)
}

// GetByID mocks base method.
func (m *MockWalletRepository) GetByID(ctx context.Context, walletID string) (*auction.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, walletID)
	ret0, _ := ret[0].(*auction.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWalletRepositoryMockRecorder) GetByID(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWalletRepository)(nil).GetByID), ctx, walletID)
}

// ListTransactionsByWalletID mocks base method.
func (m *MockWalletRepository) ListTransactionsByWalletID(ctx context.Context, walletID string) ([]*auction.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByWalletID", ctx, walletID)
	ret0, _ := ret[0].([]*auction.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByWalletID indicates an expected call of ListTransactionsByWalletID.
func (mr *MockWalletRepositoryMockRecorder) ListTransactionsByWalletID(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByWalletID", reflect.TypeOf((*MockWalletRepository)(nil).ListTransactionsByWalletID), ctx, walletID)
}

// UpdateBalance mocks base method.
func (m *MockWalletRepository) UpdateBalance(ctx context.Context, walletID string, newBalance, updatedAtMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, walletID, newBalance, updatedAtMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockWalletRepositoryMockRecorder) UpdateBalance(ctx, walletID, newBalance, updatedAtMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockWalletRepository)(nil).UpdateBalance), ctx, walletID, newBalance, updatedAtMs)
}

// DeleteAllWalletTransactionsForTournamentEvent mocks base method.
func (m *MockWalletRepository) DeleteAllWalletTransactionsForTournamentEvent(ctx context.Context, tournamentID, tournamentEventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllWalletTransactionsForTournamentEvent", ctx, tournamentID, tournamentEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllWalletTransactionsForTournamentEvent indicates an expected call of DeleteAllWalletTransactionsForTournamentEvent.
func (mr *MockWalletRepositoryMockRecorder) DeleteAllWalletTransactionsForTournamentEvent(ctx, tournamentID, tournamentEventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllWalletTransactionsForTournamentEvent", reflect.TypeOf((*MockWalletRepository)(nil).DeleteAllWalletTransactionsForTournamentEvent), ctx, tournamentID, tournamentEventID)
}

// ZeroWalletBalancesForTournamentEvent mocks base method.
func (m *MockWalletRepository) ZeroWalletBalancesForTournamentEvent(ctx context.Context, tournamentID, tournamentEventID string, updatedAtMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZeroWalletBalancesForTournamentEvent", ctx, tournamentID, tournamentEventID, updatedAtMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ZeroWalletBalancesForTournamentEvent indicates an expected call of ZeroWalletBalancesForTournamentEvent.
func (mr *MockWalletRepositoryMockRecorder) ZeroWalletBalancesForTournamentEvent(ctx, tournamentID, tournamentEventID, updatedAtMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZeroWalletBalancesForTournamentEvent", reflect.TypeOf((*MockWalletRepository)(nil).ZeroWalletBalancesForTournamentEvent), ctx, tournamentID, tournamentEventID, updatedAtMs)
}
