// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/storage/file_uploader.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockFileUploader is a mock of FileUploader interface.
type MockFileUploader struct {
	ctrl     *gomock.Controller
	recorder *MockFileUploaderMockRecorder
}

// MockFileUploaderMockRecorder is the mock recorder for MockFileUploader.
type MockFileUploaderMockRecorder struct {
	mock *MockFileUploader
}

// NewMockFileUploader creates a new mock instance.
func NewMockFileUploader(ctrl *gomock.Controller) *MockFileUploader {
	mock := &MockFileUploader{ctrl: ctrl}
	mock.recorder = &MockFileUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUploader) EXPECT() *MockFileUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockFileUploader) Upload(ctx context.Context, filename string, data []byte, contentType, folder string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, filename, data, contentType, folder)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileUploaderMockRecorder) Upload(ctx, filename, data, contentType, folder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileUploader)(nil).Upload), ctx, filename, data, contentType, folder)
}

// MockPresigner is a mock of Presigner interface.
type MockPresigner struct {
	ctrl     *gomock.Controller
	recorder *MockPresignerMockRecorder
}

// MockPresignerMockRecorder is the mock recorder for MockPresigner.
type MockPresignerMockRecorder struct {
	mock *MockPresigner
}

// NewMockPresigner creates a new mock instance.
func NewMockPresigner(ctrl *gomock.Controller) *MockPresigner {
	mock := &MockPresigner{ctrl: ctrl}
	mock.recorder = &MockPresignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresigner) EXPECT() *MockPresignerMockRecorder {
	return m.recorder
}

// Presign mocks base method.
func (m *MockPresigner) Presign(ctx context.Context, key string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Presign", ctx, key, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Presign indicates an expected call of Presign.
func (mr *MockPresignerMockRecorder) Presign(ctx, key, expiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Presign", reflect.TypeOf((*MockPresigner)(nil).Presign), ctx, key, expiry)
}
