-- Generated by scripts/generate_tournament_player_registration_sql.py
-- tournament_player_registrations: id, tournament_id, tournament_event_id, player_id, created_at

INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('05594674-bf15-4209-8c0b-99feb1a45762', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '05594674-bf15-4209-8c0b-99feb1a45762', 1777785854506);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('b017c7e0-a8d3-429d-84f2-8f0927578e5b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'b017c7e0-a8d3-429d-84f2-8f0927578e5b', 1777758261277);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0b042be5-0ba6-45cb-873b-2eddd59b502b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0b042be5-0ba6-45cb-873b-2eddd59b502b', 1777743617715);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('813353cd-2043-45a2-a7e9-f937cee36691', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '813353cd-2043-45a2-a7e9-f937cee36691', 1777741742284);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('37a4e53b-cca1-4613-b79d-7875c09f3b17', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '37a4e53b-cca1-4613-b79d-7875c09f3b17', 1777741144479);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e309deac-c8a8-4aed-bb6e-e32e8227ed6b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e309deac-c8a8-4aed-bb6e-e32e8227ed6b', 1777425128068);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('a9ea3c0e-0345-4c28-b1e3-9901bb321d38', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'a9ea3c0e-0345-4c28-b1e3-9901bb321d38', 1777389251302);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('75972b0d-c66a-41df-be09-29b62108e302', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '75972b0d-c66a-41df-be09-29b62108e302', 1777370141453);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('27dfc8a2-e44c-4a6d-b169-85d393982af2', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '27dfc8a2-e44c-4a6d-b169-85d393982af2', 1777290365544);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('733fd5f6-7967-4908-8868-659e1e658a96', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '733fd5f6-7967-4908-8868-659e1e658a96', 1777222165647);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('ca704f60-bc00-4ad3-b28c-389fb81cf018', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'ca704f60-bc00-4ad3-b28c-389fb81cf018', 1777220747792);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('fcaa1d26-a217-421e-a49a-2ffa6582cfce', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'fcaa1d26-a217-421e-a49a-2ffa6582cfce', 1777173810757);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('b40be980-0564-4eff-b7c6-76e0e99df8ad', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'b40be980-0564-4eff-b7c6-76e0e99df8ad', 1777171835363);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('df68aef5-565e-401e-b65f-8c17fc252710', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'df68aef5-565e-401e-b65f-8c17fc252710', 1777024149332);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('4756498b-33a6-43f2-ba10-7a04e0c928e9', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '4756498b-33a6-43f2-ba10-7a04e0c928e9', 1776862492598);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5d19c2b3-11f9-4a26-97d7-140246ab1d64', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5d19c2b3-11f9-4a26-97d7-140246ab1d64', 1776834182869);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e0fa2d3d-6726-4e41-9678-840e06076e7e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e0fa2d3d-6726-4e41-9678-840e06076e7e', 1776762895808);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f8da172f-765a-41f2-8f17-9e74516ce1bb', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f8da172f-765a-41f2-8f17-9e74516ce1bb', 1776691868437);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('649363f6-1fac-4f85-8797-b96f0df33d44', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '649363f6-1fac-4f85-8797-b96f0df33d44', 1776677159913);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c6b8e194-8d3b-4143-9856-5ee1c138d358', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c6b8e194-8d3b-4143-9856-5ee1c138d358', 1776672096969);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('40025aad-63fc-48e7-86b2-1309e235f69e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '40025aad-63fc-48e7-86b2-1309e235f69e', 1776583159046);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('1e1808a4-a11a-46b1-82cd-97472de06195', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '1e1808a4-a11a-46b1-82cd-97472de06195', 1776534686314);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('69dbe144-bd10-49cd-8e36-d55cd0061da6', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '69dbe144-bd10-49cd-8e36-d55cd0061da6', 1776178973026);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('ce41a23f-3e3f-4924-b241-7724c8086feb', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'ce41a23f-3e3f-4924-b241-7724c8086feb', 1776089795898);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('cc51c6d4-46ad-44c5-a64e-5557d343d7a0', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'cc51c6d4-46ad-44c5-a64e-5557d343d7a0', 1776055598317);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3be377a3-7161-4797-be1f-4c2c51a39210', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3be377a3-7161-4797-be1f-4c2c51a39210', 1775965361045);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('74a92785-a488-4d1d-b795-96dcaa215c26', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '74a92785-a488-4d1d-b795-96dcaa215c26', 1775958812894);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('2db758b1-6db2-4d9c-9b5d-0190c52438e9', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '2db758b1-6db2-4d9c-9b5d-0190c52438e9', 1775853106494);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('db271fca-cacd-4021-98d4-64a348a119ea', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'db271fca-cacd-4021-98d4-64a348a119ea', 1775834329371);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0e80327e-3e47-4098-971b-3f2838372449', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0e80327e-3e47-4098-971b-3f2838372449', 1775824175559);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('bab80f94-4772-42f0-bba3-dfd5f1b0eba9', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'bab80f94-4772-42f0-bba3-dfd5f1b0eba9', 1775670170278);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('60e8d704-b643-4404-871a-a1bccb3a61fd', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '60e8d704-b643-4404-871a-a1bccb3a61fd', 1775664714979);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('002c0d87-a4f5-42e3-a9e4-86873caf1adf', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '002c0d87-a4f5-42e3-a9e4-86873caf1adf', 1775636142856);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('921eb5e8-f42b-4838-b63c-77ea0414cc8b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '921eb5e8-f42b-4838-b63c-77ea0414cc8b', 1775634577916);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('ac6c7e3b-15d3-4d26-bd99-0329ff79d5f1', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'ac6c7e3b-15d3-4d26-bd99-0329ff79d5f1', 1775629536068);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5507d397-3255-469e-a983-f8481c66fe44', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5507d397-3255-469e-a983-f8481c66fe44', 1775572237257);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('6a85d3e3-a6bb-4e89-ac89-a76086043596', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '6a85d3e3-a6bb-4e89-ac89-a76086043596', 1775314035401);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('a5c46148-2e14-4e44-bab0-6649b6bf9e1f', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'a5c46148-2e14-4e44-bab0-6649b6bf9e1f', 1775287796690);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('51c1c1bf-5410-4111-a2bd-dd402110c190', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '51c1c1bf-5410-4111-a2bd-dd402110c190', 1775285679062);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('fcae58a3-d2d3-4469-abc7-4ba996d20315', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'fcae58a3-d2d3-4469-abc7-4ba996d20315', 1775283669178);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c440e145-5622-4d9a-9cd1-f3aee49e3db3', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c440e145-5622-4d9a-9cd1-f3aee49e3db3', 1775267932019);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('286da701-22b1-477e-b631-d8b5a89a13b6', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '286da701-22b1-477e-b631-d8b5a89a13b6', 1775237162690);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('214bb1b7-8eb1-446b-a775-bf93ef059f86', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '214bb1b7-8eb1-446b-a775-bf93ef059f86', 1775236945872);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('74de4e61-5208-4997-8335-d381790cca96', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '74de4e61-5208-4997-8335-d381790cca96', 1775149898009);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c472e736-0a63-4b4b-886a-5feeb582f91f', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c472e736-0a63-4b4b-886a-5feeb582f91f', 1775144997929);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('75e1b765-d37c-4a70-9ed2-2663ec8d6283', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '75e1b765-d37c-4a70-9ed2-2663ec8d6283', 1775137101452);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('00de5b5b-3eef-4156-8cfc-96c33befdbc9', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '00de5b5b-3eef-4156-8cfc-96c33befdbc9', 1775112334167);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c7c60c40-4807-43ff-a3b8-59b6c06a975b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c7c60c40-4807-43ff-a3b8-59b6c06a975b', 1774973122363);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('443a7db7-728a-4ccf-a988-5bc20f36b44e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '443a7db7-728a-4ccf-a988-5bc20f36b44e', 1774950474686);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('83e2185b-cc33-484a-ac19-c397810a91a6', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '83e2185b-cc33-484a-ac19-c397810a91a6', 1774947438238);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('2dea278e-9d32-4a9c-b668-61dd3614a9df', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '2dea278e-9d32-4a9c-b668-61dd3614a9df', 1774945996748);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('1589c7a4-474c-48d1-8224-56765f63db94', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '1589c7a4-474c-48d1-8224-56765f63db94', 1774945743521);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('6852b3bd-bc5b-4480-a47d-3e49a388f7a4', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '6852b3bd-bc5b-4480-a47d-3e49a388f7a4', 1774944263753);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d5d649da-30d9-45c2-9b3a-cd8346d4baef', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd5d649da-30d9-45c2-9b3a-cd8346d4baef', 1774942988365);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e51a20fc-9624-48b2-8ff7-3b14593c9671', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e51a20fc-9624-48b2-8ff7-3b14593c9671', 1774896418039);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('789687ba-28a7-4264-a2a1-619c2a5619f6', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '789687ba-28a7-4264-a2a1-619c2a5619f6', 1774892077434);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('612e41ef-6f85-4b79-a3eb-fb4177790a9e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '612e41ef-6f85-4b79-a3eb-fb4177790a9e', 1774891210053);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c0dcb650-28db-4a06-851b-6c676971b995', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c0dcb650-28db-4a06-851b-6c676971b995', 1774878118315);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d88cb2c2-f884-49ec-887d-07da5fbf68c5', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd88cb2c2-f884-49ec-887d-07da5fbf68c5', 1774877821509);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f0c5d159-5e23-4968-9a62-e3eb605c363d', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f0c5d159-5e23-4968-9a62-e3eb605c363d', 1774847772229);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f7f9ffdd-dc6d-453c-b394-1c866e93e3f5', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f7f9ffdd-dc6d-453c-b394-1c866e93e3f5', 1774830085708);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d7a17949-d96a-4bc1-9ddb-2fe68986e802', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd7a17949-d96a-4bc1-9ddb-2fe68986e802', 1774816110472);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('7ade6e5d-1468-4b5e-901a-b8c342625206', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '7ade6e5d-1468-4b5e-901a-b8c342625206', 1774813415514);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('576958bd-2d97-47eb-b79a-3a441a370572', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '576958bd-2d97-47eb-b79a-3a441a370572', 1774796742412);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f7e4c44c-2d14-41de-b761-31e059fc9849', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f7e4c44c-2d14-41de-b761-31e059fc9849', 1774780864782);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('2366f6f2-dee2-4401-ab7c-4ca6c8f36f89', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '2366f6f2-dee2-4401-ab7c-4ca6c8f36f89', 1774780399717);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0b646a12-2fe8-4b6f-9d8a-cc4efabff7d3', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0b646a12-2fe8-4b6f-9d8a-cc4efabff7d3', 1774768138043);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f7b16e4f-1ae7-437c-9bea-3cbca8a53c6a', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f7b16e4f-1ae7-437c-9bea-3cbca8a53c6a', 1774766331607);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('8f054b18-62d2-4797-bdf5-51e37200887a', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '8f054b18-62d2-4797-bdf5-51e37200887a', 1774762892908);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3e1d98b0-1df5-4ddf-b3d2-c4a5b6729aab', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3e1d98b0-1df5-4ddf-b3d2-c4a5b6729aab', 1774752467481);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('ae09b0c8-7a4a-4fd1-9872-07d4caef9dfa', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'ae09b0c8-7a4a-4fd1-9872-07d4caef9dfa', 1774703536148);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0e9aba21-d896-4206-acb3-e97e790f6148', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0e9aba21-d896-4206-acb3-e97e790f6148', 1774634689539);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('69e48cce-54ce-4980-8c39-de491099e264', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '69e48cce-54ce-4980-8c39-de491099e264', 1774618648388);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('bf1884e2-d245-43e2-9f41-f950525bd41f', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'bf1884e2-d245-43e2-9f41-f950525bd41f', 1774542740917);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('2f0a33e9-5d80-475d-817b-d72347049d2b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '2f0a33e9-5d80-475d-817b-d72347049d2b', 1774507953477);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d43a0323-7b66-4b6b-9d29-e3e77c809488', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd43a0323-7b66-4b6b-9d29-e3e77c809488', 1774505341880);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('47c1287f-0226-4571-8bd9-b712c1a09b21', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '47c1287f-0226-4571-8bd9-b712c1a09b21', 1774375026595);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('45e97e81-05b6-4e65-996a-7282fdd0a9b7', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '45e97e81-05b6-4e65-996a-7282fdd0a9b7', 1774373365047);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('a7f4eefa-54cd-493d-9f04-53622bf35c93', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'a7f4eefa-54cd-493d-9f04-53622bf35c93', 1774364441576);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('fdeb5029-5050-4f6e-a0b5-9c93ab0d1231', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'fdeb5029-5050-4f6e-a0b5-9c93ab0d1231', 1774360190329);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('ee009106-061c-4125-9baa-4024535fe423', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'ee009106-061c-4125-9baa-4024535fe423', 1774355368951);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('988f3764-87e7-4d8f-aae0-1f1520b43040', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '988f3764-87e7-4d8f-aae0-1f1520b43040', 1774277209554);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('44e3997e-2478-4aea-924f-3b6a93bc0240', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '44e3997e-2478-4aea-924f-3b6a93bc0240', 1774253144226);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('9356c938-fd4c-4c9a-b39b-d66cfa00c799', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '9356c938-fd4c-4c9a-b39b-d66cfa00c799', 1774250986936);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('bde6b135-f871-4ba2-a82e-f825005de8c3', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'bde6b135-f871-4ba2-a82e-f825005de8c3', 1774180862945);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e49f6c0c-5c9d-4aeb-ab7e-4cf066045576', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e49f6c0c-5c9d-4aeb-ab7e-4cf066045576', 1774101123329);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('95ac7d6e-92dd-4248-a6df-3ae7a7a255bc', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '95ac7d6e-92dd-4248-a6df-3ae7a7a255bc', 1774099941859);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('167fb590-c144-4c99-9854-be296d151dde', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '167fb590-c144-4c99-9854-be296d151dde', 1774093694788);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('4f904068-6ab6-4814-89bc-7f86eb2f14e5', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '4f904068-6ab6-4814-89bc-7f86eb2f14e5', 1774088120641);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('fb7a1179-c936-4398-8f90-a135e7d6b209', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'fb7a1179-c936-4398-8f90-a135e7d6b209', 1773833385978);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('de808de2-5638-4dcd-b721-aae14d2f04cc', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'de808de2-5638-4dcd-b721-aae14d2f04cc', 1773757819865);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('1acf1494-058c-426f-a489-f08bf63e47be', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '1acf1494-058c-426f-a489-f08bf63e47be', 1773751269779);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e05a4eb6-0ea8-4406-b095-4b1c0440e6ef', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e05a4eb6-0ea8-4406-b095-4b1c0440e6ef', 1773725583749);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c217eb35-0f40-46de-8d89-dfe35b1d874b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c217eb35-0f40-46de-8d89-dfe35b1d874b', 1773723247561);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('03babf04-7f22-4b0f-ae9e-580105600fca', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '03babf04-7f22-4b0f-ae9e-580105600fca', 1773672137270);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('769dfea8-4753-4e79-a0ee-2a8a9f8cce23', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '769dfea8-4753-4e79-a0ee-2a8a9f8cce23', 1773650068984);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('cddc2daf-537b-4e53-a668-b1234c771150', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'cddc2daf-537b-4e53-a668-b1234c771150', 1773571765692);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e3b15b1c-173f-4fe4-aee4-12f6b409e7ec', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e3b15b1c-173f-4fe4-aee4-12f6b409e7ec', 1773571663811);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('9c75a02f-181d-404a-8cd8-4d937c5e3062', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '9c75a02f-181d-404a-8cd8-4d937c5e3062', 1773560172281);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c313c2ca-8dbd-49fe-99b9-793559d39596', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c313c2ca-8dbd-49fe-99b9-793559d39596', 1773560019759);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f8f9c43a-68ce-4609-8a9b-27c014b87408', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f8f9c43a-68ce-4609-8a9b-27c014b87408', 1773463540499);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('1f0f9717-508f-4f5c-a52f-3487b06b289c', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '1f0f9717-508f-4f5c-a52f-3487b06b289c', 1773461283569);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('de3b6e5c-4ced-42e2-b1e5-9d617ad73dd2', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'de3b6e5c-4ced-42e2-b1e5-9d617ad73dd2', 1773453482609);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e26b641c-8071-4963-bbf9-1aa28660bac8', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e26b641c-8071-4963-bbf9-1aa28660bac8', 1773422333790);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0d396407-1b30-4d04-ac69-7a257431057c', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0d396407-1b30-4d04-ac69-7a257431057c', 1773402060427);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3146010f-3bd8-4089-a777-9c8b66759000', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3146010f-3bd8-4089-a777-9c8b66759000', 1773394126245);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('b35b7f2a-9839-44a2-ad8d-37f7aee31bb2', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'b35b7f2a-9839-44a2-ad8d-37f7aee31bb2', 1773393831590);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('a3c496ae-0898-4381-ab10-d5ea35c3fa77', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'a3c496ae-0898-4381-ab10-d5ea35c3fa77', 1773390517164);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5419a914-4f59-48f0-9c68-7fc804f98737', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5419a914-4f59-48f0-9c68-7fc804f98737', 1773388100771);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('a9537b17-bafb-4b33-b1af-d7cc714fd111', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'a9537b17-bafb-4b33-b1af-d7cc714fd111', 1773384892744);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3ea74d31-9c89-40f9-95c0-08f784882df0', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3ea74d31-9c89-40f9-95c0-08f784882df0', 1773370903397);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('427a275b-4062-442a-adba-5ba1d2c75427', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '427a275b-4062-442a-adba-5ba1d2c75427', 1773350253313);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('130b0106-078e-48f9-8478-117cd071e226', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '130b0106-078e-48f9-8478-117cd071e226', 1773326548320);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('33bb982e-158d-45b0-9a0b-d92d79fae61b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '33bb982e-158d-45b0-9a0b-d92d79fae61b', 1773318230009);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('66b36a47-e83a-4fb0-8f20-cee43de8d423', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '66b36a47-e83a-4fb0-8f20-cee43de8d423', 1773309748038);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('26aa5100-8ebd-48ca-b6d1-1b1bd755c232', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '26aa5100-8ebd-48ca-b6d1-1b1bd755c232', 1773308536679);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('71636e7c-7d28-4e5f-b9be-d0ad50ba38f8', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '71636e7c-7d28-4e5f-b9be-d0ad50ba38f8', 1773307739662);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('93617769-f00d-45f8-af1d-5cdfb6ba5527', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '93617769-f00d-45f8-af1d-5cdfb6ba5527', 1773301190215);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0c8c6d0b-8e6d-462b-8af7-614ed1225d71', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0c8c6d0b-8e6d-462b-8af7-614ed1225d71', 1773238048422);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('78563d29-cac4-4fbe-ad95-b317024ab2c4', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '78563d29-cac4-4fbe-ad95-b317024ab2c4', 1773234744216);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e418bc3e-66d0-46a0-9dd8-963d419fd34c', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e418bc3e-66d0-46a0-9dd8-963d419fd34c', 1773232355911);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d0c1b42e-bf15-4c4b-89ee-1b3bf2001f81', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd0c1b42e-bf15-4c4b-89ee-1b3bf2001f81', 1773232102186);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('42146cc4-a7cc-41b5-99d8-769ff9eead1b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '42146cc4-a7cc-41b5-99d8-769ff9eead1b', 1773231592615);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('e90b8f49-8b7f-4c08-b6b0-7752497b4d8e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'e90b8f49-8b7f-4c08-b6b0-7752497b4d8e', 1773218044839);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('841d21bb-a05b-4951-b5f7-31e6a6a2c061', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '841d21bb-a05b-4951-b5f7-31e6a6a2c061', 1773206918394);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('903316cf-d444-43bc-a5d9-6a4842cdbea1', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '903316cf-d444-43bc-a5d9-6a4842cdbea1', 1773196068179);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5389f98f-3c66-4b57-91f3-6e05f81a757f', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5389f98f-3c66-4b57-91f3-6e05f81a757f', 1773195859061);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('91c6b484-4056-4f90-83aa-b256e9031186', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '91c6b484-4056-4f90-83aa-b256e9031186', 1773161874869);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('22ae4885-f58a-4685-a92f-47e0c94cc293', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '22ae4885-f58a-4685-a92f-47e0c94cc293', 1773160392655);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('efae80ee-32b5-42b8-857a-5811f42767eb', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'efae80ee-32b5-42b8-857a-5811f42767eb', 1773160277036);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('b7a54375-9a52-45cf-9b1c-9cec35d0c98a', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'b7a54375-9a52-45cf-9b1c-9cec35d0c98a', 1773160250825);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3c942733-e160-4bb3-a07d-e5db79fb1692', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3c942733-e160-4bb3-a07d-e5db79fb1692', 1773150096784);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('09b0c1b7-1fde-4441-9f61-4e658da518fa', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '09b0c1b7-1fde-4441-9f61-4e658da518fa', 1773148453520);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('7a15d26f-9713-48f5-84c8-eac0d392c51f', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '7a15d26f-9713-48f5-84c8-eac0d392c51f', 1773145783597);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('869725a3-a75f-439a-a4f9-6d01fba74c3a', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '869725a3-a75f-439a-a4f9-6d01fba74c3a', 1773143376407);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5adf3a79-97d7-4b9a-b897-0fa8cd323abd', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5adf3a79-97d7-4b9a-b897-0fa8cd323abd', 1773135619354);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('feddba70-896c-47bd-aca7-43616528e847', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'feddba70-896c-47bd-aca7-43616528e847', 1773134525690);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('23d83ce2-74e6-46fb-a4ae-602d16dd8e47', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '23d83ce2-74e6-46fb-a4ae-602d16dd8e47', 1773131358586);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3b8c0bc1-4251-45f8-bbc0-9b95ed832d3f', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3b8c0bc1-4251-45f8-bbc0-9b95ed832d3f', 1773125488531);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('2081e937-b9ee-4309-b961-982c14b4413a', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '2081e937-b9ee-4309-b961-982c14b4413a', 1773125138642);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('01f65128-d758-41b8-a2b7-26728a491219', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '01f65128-d758-41b8-a2b7-26728a491219', 1773124480582);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('2f55a74b-e695-43a0-afbd-a8b5c53bf3a4', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '2f55a74b-e695-43a0-afbd-a8b5c53bf3a4', 1773124118410);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('347ce114-1f99-4c61-a6ce-2990d7189f6a', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '347ce114-1f99-4c61-a6ce-2990d7189f6a', 1773123835706);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('036010f5-03cf-47d4-9416-6ad2b5aa1846', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '036010f5-03cf-47d4-9416-6ad2b5aa1846', 1773123784732);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('00b0f860-f6f5-4046-ae4a-f7674ca5e182', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '00b0f860-f6f5-4046-ae4a-f7674ca5e182', 1773123137914);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('c6fe7db8-2e25-45ed-b96a-b82ddf01085c', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'c6fe7db8-2e25-45ed-b96a-b82ddf01085c', 1773120787532);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('32d1e050-254f-4410-8405-74ec885369f3', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '32d1e050-254f-4410-8405-74ec885369f3', 1773115518907);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('163559ef-9991-4119-ba92-3257954add00', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '163559ef-9991-4119-ba92-3257954add00', 1773115459772);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('8c2660a5-b954-4a58-bf53-2047332d964b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '8c2660a5-b954-4a58-bf53-2047332d964b', 1773114239835);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('54166033-5289-4e28-a328-fd5ffe92978e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '54166033-5289-4e28-a328-fd5ffe92978e', 1773113414470);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('ab7be312-6523-4ba3-9525-a04228bff9ff', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'ab7be312-6523-4ba3-9525-a04228bff9ff', 1773112487011);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('3b51f487-15cb-4978-9939-64a569ff15c1', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '3b51f487-15cb-4978-9939-64a569ff15c1', 1773110327554);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('58ab2bf2-50f7-4d69-b11a-86a6cb484535', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '58ab2bf2-50f7-4d69-b11a-86a6cb484535', 1773110278272);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('7b4d91b4-fc2d-4e3c-9f48-c692b2447b70', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '7b4d91b4-fc2d-4e3c-9f48-c692b2447b70', 1773081932489);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('52b12fa5-189a-4d02-adb5-0f755a94461d', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '52b12fa5-189a-4d02-adb5-0f755a94461d', 1773080481746);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('4a2b5863-ec6b-4b03-8c34-350d2748e07e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '4a2b5863-ec6b-4b03-8c34-350d2748e07e', 1773078879238);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('6f6a1dc3-b01a-4fe7-a1c4-3dd27cd4ecbe', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '6f6a1dc3-b01a-4fe7-a1c4-3dd27cd4ecbe', 1773075531234);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('94d38401-f438-4018-941e-71cfe60d7f3c', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '94d38401-f438-4018-941e-71cfe60d7f3c', 1773070946119);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('75eb8603-6639-43fa-af98-19471d3024d0', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '75eb8603-6639-43fa-af98-19471d3024d0', 1773070883240);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('cb99dedb-3839-4326-aeb4-76ae01d99be6', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'cb99dedb-3839-4326-aeb4-76ae01d99be6', 1773070568144);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('fc4a7be8-1538-4af6-b68f-cc62690c4aad', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'fc4a7be8-1538-4af6-b68f-cc62690c4aad', 1773070468923);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d532b5f7-9f27-4a16-9e38-cfca4e57ecb1', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd532b5f7-9f27-4a16-9e38-cfca4e57ecb1', 1773070250303);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5101974e-7e93-446c-b6ca-63ed05257165', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5101974e-7e93-446c-b6ca-63ed05257165', 1773069733120);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('d258c23d-b03c-4c94-a87c-d1fa3b7b9f50', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'd258c23d-b03c-4c94-a87c-d1fa3b7b9f50', 1773069492548);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('115125c2-acec-4ced-9888-0601f010360e', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '115125c2-acec-4ced-9888-0601f010360e', 1773069067027);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('b7727362-a164-45e7-afdc-9a5a82fdf1b7', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'b7727362-a164-45e7-afdc-9a5a82fdf1b7', 1773069056615);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f5ec117c-01e9-40d7-8ff3-cf7c33fcfe1c', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f5ec117c-01e9-40d7-8ff3-cf7c33fcfe1c', 1773068760206);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('0e0ce485-8301-414a-b3c2-2013bfc30699', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '0e0ce485-8301-414a-b3c2-2013bfc30699', 1773068669432);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('f47ce887-bf86-4e04-b3f1-d81b88fce22b', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'f47ce887-bf86-4e04-b3f1-d81b88fce22b', 1773068533609);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('5883f0ad-784f-41e3-8558-2e24006cde83', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '5883f0ad-784f-41e3-8558-2e24006cde83', 1773064806168);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('a37f4011-8ceb-4d9c-b549-c08347ce76dd', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', 'a37f4011-8ceb-4d9c-b549-c08347ce76dd', 1773064210604);
INSERT INTO public.tournament_player_registrations(id, tournament_id, tournament_event_id, player_id, created_at)
VALUES ('395a1116-c12f-4909-b412-aa8577f06eb7', 'a0000001-0000-4000-8000-000000000001', 'a0000002-0000-4000-8000-000000000001', '395a1116-c12f-4909-b412-aa8577f06eb7', 1773064099850);
