#!/usr/bin/env python3
"""
Read players.csv and emit INSERTs for public.tournament_player_registrations.

By default registration id and player_id both use the CSV `id` column (same as players.id);
created_at uses the CSV `created_at` column.

Usage:
  python scripts/generate_tournament_player_registration_sql.py > inserts.sql
  python scripts/generate_tournament_player_registration_sql.py --csv path/to/players.csv

  # If you want a new UUID per registration row (player_id still from CSV id):
  python scripts/generate_tournament_player_registration_sql.py --new-registration-id
"""

from __future__ import annotations

import argparse
import csv
import sys
import uuid
from pathlib import Path


DEFAULT_TOURNAMENT_ID = "a0000001-0000-4000-8000-000000000001"
DEFAULT_TOURNAMENT_EVENT_ID = "a0000002-0000-4000-8000-000000000001"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--csv",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "players.csv",
        help="Path to players.csv (default: repo root players.csv)",
    )
    p.add_argument("--tournament-id", default=DEFAULT_TOURNAMENT_ID)
    p.add_argument("--tournament-event-id", default=DEFAULT_TOURNAMENT_EVENT_ID)
    p.add_argument(
        "--new-registration-id",
        action="store_true",
        help="Generate a new UUID for each registration id (player_id still from CSV id).",
    )
    args = p.parse_args()

    if not args.csv.is_file():
        print(f"error: file not found: {args.csv}", file=sys.stderr)
        sys.exit(1)

    tid = args.tournament_id.replace("'", "''")
    teid = args.tournament_event_id.replace("'", "''")

    with args.csv.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames or "id" not in reader.fieldnames:
            print("error: CSV must have an 'id' column", file=sys.stderr)
            sys.exit(1)
        if "created_at" not in reader.fieldnames:
            print("error: CSV must have a 'created_at' column", file=sys.stderr)
            sys.exit(1)

        print(
            "-- Generated by scripts/generate_tournament_player_registration_sql.py\n"
            "-- tournament_player_registrations: id, tournament_id, tournament_event_id, player_id, created_at\n"
        )

        for row in reader:
            player_id = (row.get("id") or "").strip().strip('"')
            if not player_id:
                continue
            created_raw = (row.get("created_at") or "").strip().strip('"')
            if not created_raw:
                print(
                    f"-- skip row without created_at: player_id={player_id!r}",
                    file=sys.stderr,
                )
                continue
            try:
                created_at = int(created_raw)
            except ValueError:
                print(
                    f"-- skip invalid created_at {created_raw!r} for player {player_id}",
                    file=sys.stderr,
                )
                continue

            if args.new_registration_id:
                reg_id = str(uuid.uuid4())
            else:
                reg_id = player_id

            # PostgreSQL literals
            reg_esc = reg_id.replace("'", "''")
            pid_esc = player_id.replace("'", "''")

            print(
                "INSERT INTO public.tournament_player_registrations"
                "(id, tournament_id, tournament_event_id, player_id, created_at)\n"
                f"VALUES ('{reg_esc}', '{tid}', '{teid}', '{pid_esc}', {created_at});"
            )


if __name__ == "__main__":
    main()
